global:
  affinity: &affinity
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cloud.google.com/gke-nodepool
            operator: In
            values:
            - argilla

argilla:
  replicaCount: 1
  image:
    repository: argilla/argilla-server
    tag: v2.5.0
  resources:
    requests:
      cpu: "1"
      memory: "1Gi"
    limits:
      memory: "2Gi"
  auth:
    username: "argilla"
    existingSecret: "argilla"
    secretKeys:
      ownerPassword: ownerPassword
      ownerApiKey: ownerApiKey
      authSecretKey: authSecretKey
  databaseUrl: "postgresql+asyncpg://argilla:argilla@argilla-postgresql.argilla.svc.cluster.local:5432/argilla"
  persistence:
    enabled: false
    accessMode: ReadWriteMany
    size: 2Gi
    mountPath: "/data"
  ingress:
    enabled: true
    className: "nginx"
    host: "airflow.example.com"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/use-regex: "true"
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
  affinity: *affinity

elasticsearch:
  host: "http://argilla-elasticsearch.argilla.svc.cluster.local"
  port: 9200
  path: "/es"

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    affinity: *affinity
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 1Gi
      resources:
        requests:
          cpu: 0.25
          memory: 1Gi
        limits:
          cpu: 1
          memory: 2Gi
serviceAccount:
  create: false

worker:
  replicaCount: 1
  numWorkers: 2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  affinity: *affinity
