apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argilla.fullname" . }}
  labels:
    {{- include "argilla.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.argilla.replicaCount }}
  selector:
    matchLabels:
      {{- include "argilla.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "argilla.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      {{- if .Values.argilla.persistence.enabled }}
        - name: argilla-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.argilla.image.repository }}:{{ .Values.argilla.image.tag }}"
          env:
            - name: ARGILLA_ELASTICSEARCH
              value: "{{ .Values.elasticsearch.host }}:{{ .Values.elasticsearch.port }}"
            - name: ARGILLA_AUTH_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.argilla.auth.existingSecret }}
                  key:  {{ .Values.argilla.auth.secretKeys.authSecretKey }}
            - name: ARGILLA_REDIS_URL
              value: redis://{{ .Release.Name }}-redis-master:6379/0
            - name: USERNAME
              value: {{ .Values.argilla.auth.username | quote }}
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.argilla.auth.existingSecret }}
                  key:  {{ .Values.argilla.auth.secretKeys.ownerPassword }}
            - name: ARGILLA_DATABASE_URL
              value: {{ .Values.argilla.databaseUrl | quote }}
            {{- if .Values.argilla.persistence.enabled }}
            - name: ARGILLA_HOME_PATH
              value: {{ .Values.argilla.persistence.mountPath | quote }}
            {{- end }}
            - name: ARGILLA_BASE_URL
              values: {{ .Values.argilla.host | quote }}
          ports:
            - containerPort: 6900
          volumeMounts:
          {{- if .Values.argilla.persistence.enabled }}
            - name: argilla-data
              mountPath: {{ .Values.argilla.persistence.mountPath}}
          {{- end }}
          resources:
            {{- toYaml .Values.argilla.resources | nindent 12 }}
{{- if .Values.argilla.affinity }}
    affinity:
{{ toYaml .Values.argilla.affinity | indent 6 }}
{{- end }}
{{- if .Values.argilla.tolerations }}
    tolerations:
{{ toYaml .Values.argilla.tolerations | indent 6 }}
{{- end }}